version: '2'
services:
  myapp:
    image: 'cerdom:latest'
    ports:
      - '8000:8000'
    volumes:
      - '.:/var/www/html/cerdom'
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:11.2-alpine
    container_name: cerdom-postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dbcerdom
